### ISSUE TITLE
Support eclipse 4.4. (luna release)

### ISSUE THREAD

**Issue by alaendle** [scalastyle/scalastyle-plugin#18]

**Comment by matthewfarwell** [comment]
And it's done.

http://www.scalastyle.org/downloads/luna-0.6.1/site/

Could you try this and tell me if it works for you.

Thanks.

Matthew Farwell.

2014-12-30 10:43 GMT+01:00 Matthew Farwell <matthew@farwell.co.uk>:

**Comment by mlangc** [comment]
Hmm, maybe I'm doing something wrong, but although the preference page seems to work fine, I can't see the warnings reported by the SBT plugin in the editor (using the same configuration). Is it possible that this has something to do with the fact that I'm using a locally build version of scala-ide?

**Comment by matthewfarwell** [comment]
Have you done all of the normal things like rebuild everything - make sure
there are no errors in the error log and make sure that you have scalastyle
nature and scalastyle is activated for the project, and the configuration
is the same one that you are using from sbt?

If all looks ok, can you provide a sample project which doesn't work?

Thanks.

Matthew Farwell.

2015-01-02 9:14 GMT+01:00 Matthias Langer <notifications@github.com>:

**Comment by mlangc** [comment]
You can find a sample project, together with the related log files [here](https://spideroak.com/browse/share/lolukukassus/scalastyle/scalastyle/issue-18/). Using the SBT plugin, I get several warnings, but I can't see any of them in the IDE. I tested against a vanilla version of Scala-IDE-4.0.0.

Thank you very much,
Matthias

**Comment by matthewfarwell** [comment]
Sorry, can't reproduce it :-) Please see attached images. The version of
scala-ide should not make a difference, but i'm using 4.0.0 rc2.

Are you using 0.6.1?

Have fun,

Matthew Farwell.

[image: Images intégrées 2][image: Images intégrées 1]

2015-01-04 18:02 GMT+01:00 Matthias Langer <notifications@github.com>:

**Comment by mlangc** [comment]
Yea, I'm using the version from http://www.scalastyle.org/downloads/luna-0.6.1/site/. Let's see if I'm the only one affected by this...

**Comment by matthewfarwell** [comment]
OK. If it happens again, contact me and we'll try and get to the bottom of
it.

Matthew Farwell.

**Comment by alaendle** [comment]
v0.6.1 works fine for me - many thanks :+1:

**Comment by BasilBibi** [comment]
Hi Matthew - Sorry If I'm being stupid but I cannot see any instructions for building the plugin.
When I try to build it fails because eclipse.codename which is not defined
I also see that http://www.scalastyle.org/downloads/kepler-0.8.0/site/ points to the exact same page.
I was hoping to get a prebuilt plugin which I was expecting to find there.
I have scalaIDE installed.
What am I doing wrong?
